// Sancy Wandelkaart - Data
// 20 Balades Thématiques van het Massif du Sancy
// Bron: informatieborden ter plaatse

const TRAILS = [
  {
    id: 1,
    name: "Sur les traces de l'ancien funiculaire",
    gemeente: "La Bourboule",
    afstand: "3.5 km",
    duur: "1u30",
    hoogteverschil: "329 m",
    moeilijkheid: "moeilijk",
    beschrijving: "Sportieve wandeling in de voetsporen van de oude kabelspoorweg (1902-1958) van La Bourboule. Vanuit het Parc Fenestre volgt het pad de overblijfselen van dit ingenieuze waterballastsysteem door de bossen naar het plateau van Charlannes.",
    startPunt: [45.5878, 2.7381],
    hoogtepunten: ["Ancien funiculaire", "Parc Fenestre", "Plateau de Charlannes", "Uitzicht over La Bourboule"],
    gpx: "gpx/route-1-la-bourboule.gpx",
    url: "https://www.sancy.com/circuits/sancy-tour-parcours-decouverte-sancy/sancy-tour-n1-sportif-traces-de-lancien-funiculaire-bourboule/"
  },
  {
    id: 2,
    name: "Le chemin de l'estive ovine",
    gemeente: "Murat-le-Quaire",
    afstand: "4.3 km",
    duur: "1u30",
    hoogteverschil: "158 m",
    moeilijkheid: "gemiddeld",
    beschrijving: "Ontdek de wereld van de schapenhouderij en de zomeralmen in de open landschappen rond de Banne d'Ordanche (1515 m). Onderweg leert u alles over het lokale Rava-schapenras, de bergfauna en de eeuwenoude traditie van de estive.",
    startPunt: [45.6050, 2.7580],
    hoogtepunten: ["Banne d'Ordanche (1515 m)", "Rava-schapen", "Panorama Puy de Sancy", "Bergweiden"],
    gpx: "gpx/route-2-murat-le-quaire.gpx",
    url: "https://www.sancy.com/circuits/sancy-tour-parcours-decouverte-sancy/sancy-tour-n2-chemin-de-lestive-ovine-murat-quaire/"
  },
  {
    id: 3,
    name: "Sylvatorium",
    gemeente: "Le Mont-Dore",
    afstand: "1.0 km",
    duur: "0u45",
    hoogteverschil: "20 m",
    moeilijkheid: "makkelijk",
    beschrijving: "Het eerste sylvatische pad van Frankrijk: een zintuiglijk bosbadparcours in het bos van de Capucin. Vijf houten 'bos-spa\u2019s', twee uitkijkpunten en een ontspanningsruimte. Ideaal voor gezinnen, volledig zonder hoogteverschil.",
    startPunt: [45.5640, 2.8050],
    hoogtepunten: ["5 bos-spa's", "2 uitkijkpunten", "Ontspanningsruimte", "Zintuiglijk parcours"],
    gpx: "gpx/route-3-le-mont-dore.gpx",
    url: "https://www.sancy.com/circuits/sancy-tour-parcours-decouverte-sancy/sancy-tour-n3-sylvatorium-mont-dore/"
  },
  {
    id: 4,
    name: "Les pentes du château",
    gemeente: "Murol",
    afstand: "4.8 km",
    duur: "1u30",
    hoogteverschil: "170 m",
    moeilijkheid: "gemiddeld",
    beschrijving: "Een van de sterren van de Sancy: het beroemde 12e-eeuwse kasteel van Murol onthult zijn geheimen. Van het dorp naar het Parc du Prelong, langs het kasteel en de kerk, ontvouwt het rijke erfgoed zich stap voor stap.",
    startPunt: [45.5720, 2.9450],
    hoogtepunten: ["Chateau de Murol (12e eeuw)", "Parc du Prelong", "Kerk", "Uitzicht op Lac Chambon"],
    gpx: "gpx/route-4-murol.gpx",
    url: "https://www.sancy.com/circuits/sancy-tour-parcours-decouverte-sancy/sancy-tour-n4-pentes-chateau-murol/"
  },
  {
    id: 5,
    name: "Balade au pas de l'âne",
    gemeente: "Chambon-sur-Lac",
    afstand: "5.8 km",
    duur: "2u00",
    hoogteverschil: "132 m",
    moeilijkheid: "gemiddeld",
    beschrijving: "Met de ezel met de lier als gids ontdekt u het natuurlijke en culturele erfgoed van Chambon-sur-Lac. Van schilders die zich lieten inspireren tot het Auvergnatische vulkanisme, met een romaans baptisterium uit de 10e-12e eeuw.",
    startPunt: [45.5730, 2.8650],
    hoogtepunten: ["Lac Chambon", "Dent du Marais", "Romaans baptisterium", "Vallee de Chaudefour"],
    gpx: "gpx/route-5-chambon-sur-lac.gpx",
    url: "https://www.sancy.com/circuits/sancy-tour-parcours-decouverte-sancy/sancy-tour-n5-balade-de-lane-chambon-lac/"
  },
  {
    id: 6,
    name: "Les chemins de Saint-Nectaire",
    gemeente: "Saint-Nectaire",
    afstand: "3.7 km",
    duur: "1u30",
    hoogteverschil: "106 m",
    moeilijkheid: "makkelijk",
    beschrijving: "Ontdek het duizendjarig erfgoed van dit beroemde kaasdorp met schitterende uitzichten op de Sancy. Inclusief het bijzondere zoutmoeras met maritieme plantensoorten, een Natura 2000-gebied midden in het dorp.",
    startPunt: [45.5870, 2.9930],
    hoogtepunten: ["Eglise romane", "Thermale bronnen", "Zoutmoeras (Natura 2000)", "Dolmens en menhirs"],
    gpx: "gpx/route-6-saint-nectaire.gpx",
    url: "https://www.sancy.com/circuits/sancy-tour-parcours-decouverte-sancy/sancy-tour-n6-chemins-saint-nectaire/"
  },
  {
    id: 7,
    name: "Balade Zen",
    gemeente: "Le Vernet-Sainte-Marguerite",
    afstand: "5.9 km",
    duur: "2u00",
    hoogteverschil: "124 m",
    moeilijkheid: "gemiddeld",
    beschrijving: "Ontspannende zen-wandeling met prachtige uitzichten op het Sancy-massief vanaf de Puy d'Alou (360° panorama). Onderweg passeert u het 12e-eeuwse kerkje, de bruisende Sainte-Marguerite-bron en traditionele Auvergnatische huizen.",
    startPunt: [45.6050, 2.9200],
    hoogtepunten: ["Puy d'Alou (360° panorama)", "12e-eeuwse kerk", "Bron Sainte-Marguerite", "Traditionele huizen"],
    gpx: "gpx/route-7-le-vernet.gpx",
    url: "https://www.sancy.com/circuits/sancy-tour-parcours-decouverte-sancy/sancy-tour-n7-balade-zen-vernet-sainte-marguerite/"
  },
  {
    id: 8,
    name: "Sur les pas d'un géologue",
    gemeente: "Saint-Victor-la-Rivière",
    afstand: "4.8 km",
    duur: "2u00",
    hoogteverschil: "179 m",
    moeilijkheid: "gemiddeld",
    beschrijving: "Kruip in de huid van een geologische detective en ontcijfer de raadsels van de vallei van Jassat. Dit themapad onthult de vulkanische geschiedenis en voert langs bakovens, wasplaatsen en kaaskelders van het rijke boerenleven.",
    startPunt: [45.5350, 2.9550],
    hoogtepunten: ["Vallei van Jassat", "Vulkaan Tartaret", "Bakovens en wasplaatsen", "Panorama Monts Dore"],
    gpx: "gpx/route-8-saint-victor.gpx",
    url: "https://www.sancy.com/circuits/sancy-tour-parcours-decouverte-sancy/sancy-tour-n8-dun-geologue-saint-victor-riviere/"
  },
  {
    id: 9,
    name: "Du calvaire au royaume des cieux",
    gemeente: "Saint-Pierre-Colamine",
    afstand: "7.3 km",
    duur: "2u30",
    hoogteverschil: "283 m",
    moeilijkheid: "moeilijk",
    beschrijving: "Een mix van mysterie, adembenemende uitzichtpunten en flinke klimmetjes. Ontdek het middeleeuwse grotwoningcomplex Grottes de Jonas (met fresco's) en het 360° panorama vanaf de Pic Saint-Pierre over de Chaine des Puys en de Sancy.",
    startPunt: [45.5400, 2.9780],
    hoogtepunten: ["Grottes de Jonas (fresco's)", "Pic Saint-Pierre (360°)", "Croix du Juge", "Lomprat"],
    gpx: "gpx/route-9-saint-pierre-colamine.gpx",
    url: "https://www.sancy.com/circuits/sancy-tour-parcours-decouverte-sancy/sancy-tour-n9-calvaire-royaume-cieux-saint-pierre-colamine/"
  },
  {
    id: 10,
    name: "Au fil de l'eau",
    gemeente: "Saint-Diéry",
    afstand: "4.7 km",
    duur: "1u30",
    hoogteverschil: "71 m",
    moeilijkheid: "makkelijk",
    beschrijving: "Water en al zijn gebruiken kenmerken het dorp Saint-Diery. Ontdek het overdekte washuis, de ijzerhoudende bron, de beroemde Cheminee des Fees (aardpilaar) en de mineraalwaterbron die al sinds 1872 bekend is.",
    startPunt: [45.5610, 2.9750],
    hoogtepunten: ["Cheminee des Fees", "IJzerhoudende bron", "Mineraalwater Saint-Diery", "Middeleeuws kasteel"],
    url: "https://www.sancy.com/decouvrir/toutes-les-communes/saint-diery/"
  },
  {
    id: 11,
    name: "La vallée magique",
    gemeente: "Besse-et-Saint-Anastaise",
    afstand: "3.2 km",
    duur: "1u30",
    hoogteverschil: "82 m",
    moeilijkheid: "makkelijk",
    beschrijving: "Besse biedt zowel een rijk middeleeuws erfgoed als wilde natuur. Kinderen Neon en Neoli zijn uw speelse gidsen door de magische vallei, met informatie over het vulkanisme dat de Sancy-landschappen heeft gevormd.",
    startPunt: [45.5120, 2.9370],
    hoogtepunten: ["Middeleeuws stadje Besse", "Magische vallei", "Vulkanisme", "Wilde natuur"],
    gpx: "gpx/route-11-besse.gpx",
    url: "https://www.sancy.com/circuits/sancy-tour-parcours-decouverte-sancy/sancy-tour-n11-besse-vallee-magique/"
  },
  {
    id: 12,
    name: "Le sentier des légendes",
    gemeente: "La Godivelle",
    afstand: "6.3 km",
    duur: "1u30",
    hoogteverschil: "101 m",
    moeilijkheid: "gemiddeld",
    beschrijving: "In het hart van de Cezallier vertellen de legendes zich langs twee kratermeren en beschermde veengebieden. La Godivelle: slechts 24 inwoners op 1205 m hoogte, het kleinste en hoogstgelegen dorp van de Puy-de-Dome.",
    startPunt: [45.3890, 2.8860],
    hoogtepunten: ["Lac d'en Haut", "Lac d'en Bas", "Reserve des Sagnes (144 ha)", "Veengebied"],
    gpx: "gpx/route-12-la-godivelle.gpx",
    url: "https://www.sancy.com/circuits/sancy-tour-parcours-decouverte-sancy/sancy-tour-n12-sentier-legendes-godivelle/"
  },
  {
    id: 13,
    name: "Le chemin des Ségures",
    gemeente: "Compains",
    afstand: "7.0 km",
    duur: "2u00",
    hoogteverschil: "160 m",
    moeilijkheid: "gemiddeld",
    beschrijving: "Volg het pad dat schoolkinderen van weleer dagelijks te voet aflegden en ontdek het erfgoed van Compains. Uitgestrekte basaltplateaus, burons, de romaanse kerk Saint-Georges en de mysterieuze heuvel van Brion in dit AOP Saint-Nectaire-gebied.",
    startPunt: [45.4300, 2.9600],
    hoogtepunten: ["Motte de Brion", "Kerk Saint-Georges", "Lac du Montcineyre", "Beukenbos"],
    gpx: "gpx/route-13-compains.gpx",
    url: "https://www.sancy.com/circuits/sancy-tour-parcours-decouverte-sancy/sancy-tour-n13-chemin-ecoliers-compains/"
  },
  {
    id: 14,
    name: "Les secrets de Valbeleix",
    gemeente: "Valbeleix",
    afstand: "2.1 km",
    duur: "1u00",
    hoogteverschil: "78 m",
    moeilijkheid: "makkelijk",
    beschrijving: "Op de grens van de Sancy en de Cezallier onthult een fictieve kasteelheer de geheimen van Valbeleix. Ontdek de Roche Nite (lavatand op 1150 m) en de Gallo-Romeinse brug over de Couze — een verborgen paradijsje.",
    startPunt: [45.4540, 2.9750],
    hoogtepunten: ["Roche Nite (1150 m)", "Gallo-Romeinse brug", "Plateau de la Chavade"]
  },
  {
    id: 15,
    name: "Les marchands de toile",
    gemeente: "Espinchal",
    afstand: "4.1 km",
    duur: "1u30",
    hoogteverschil: "150 m",
    moeilijkheid: "gemiddeld",
    beschrijving: "Ga mee met Baptistou die het verhaal vertelt van de stoffenhandelaren (marskramers) en de geschiedenis van Espinchal op het Cezallier-plateau. Ontdek de imposante Croix du Marquis en geniet van wijdse uitzichten vanaf de dorpshoogten.",
    startPunt: [45.4150, 2.9350],
    hoogtepunten: ["Croix du Marquis", "Kerk Saint-Nicolas (1157)", "Stoffenhandelaren", "Panorama Cezallier"],
    gpx: "gpx/route-15-espinchal.gpx",
    url: "https://www.sancy.com/circuits/sancy-tour-parcours-decouverte-sancy/sancy-tour-n15-marchands-de-toile-espinchal/"
  },
  {
    id: 16,
    name: "Le sentier des burons",
    gemeente: "Montgreleix",
    afstand: "6.0 km",
    duur: "2u00",
    hoogteverschil: "140 m",
    moeilijkheid: "gemiddeld",
    beschrijving: "Midden in de uitgestrekte weidegronden van de Cezallier leidt dit pad langs de burons: traditionele stenen kaasmakerijen met leistenen daken, van mei tot oktober bewoond. Adembenemende panorama's op de Sancy en de bergen van de Cantal.",
    startPunt: [45.4290, 2.8100],
    hoogtepunten: ["Burons (stenen kaasmakerijen)", "Veengebieden", "Panorama Sancy en Cantal", "AOP Saint-Nectaire"],
    gpx: "gpx/route-16-montgreleix.gpx",
    url: "https://www.sancy.com/circuits/sancy-tour-parcours-decouverte-sancy/sancy-tour-n-16-sentier-burons-montgreleix/"
  },
  {
    id: 17,
    name: "Le chemin des maquisards",
    gemeente: "Saint-Genès-Champespe",
    afstand: "5.8 km",
    duur: "1u30",
    hoogteverschil: "154 m",
    moeilijkheid: "gemiddeld",
    beschrijving: "Saint-Genes-Champespe heeft een bijzondere band met het verzet tijdens WOII. Deze wandeling voert langs herdenkingsplekken van de maquisards van 1944, door bossen, langs meren en weiden op het plateau van de Artense.",
    startPunt: [45.4450, 2.7650],
    hoogtepunten: ["Herdenkingsplekken verzet", "Heide (Natura 2000)", "Meren en weiden", "Plateau Artense"],
    gpx: "gpx/route-17-saint-genes.gpx",
    url: "https://www.sancy.com/circuits/sancy-tour-parcours-decouverte-sancy/sancy-tour-n17-chemin-maquisards-saint-genes-champespe/"
  },
  {
    id: 18,
    name: "De vachas, de mounde, de froumajou",
    gemeente: "Egliseneuve-d'Entraigues",
    afstand: "7.9 km",
    duur: "2u30",
    hoogteverschil: "172 m",
    moeilijkheid: "gemiddeld",
    beschrijving: "Volg Julia, Toinou en hun ezel Ficele en ontdek de bakermat van de Saint-Nectaire kaas. Van de watervallen tot de kerk, van historische overblijfselen tot de geheimen van de kaasmakerij, met een paar woorden Occitaans patois als bonus!",
    startPunt: [45.4080, 2.8261],
    hoogtepunten: ["Maison des Fromages", "Cascades d'Entraigues", "AOP Saint-Nectaire", "Blauwe leistenen daken"],
    gpx: "gpx/route-18-egliseneuve.gpx",
    url: "https://www.sancy.com/circuits/sancy-tour-parcours-decouverte-sancy/sancy-tour-n18-de-vachas-de-mounde-de-fromajou-egliseneuve-dentraigues/"
  },
  {
    id: 19,
    name: "Et si Picherande m'était conté",
    gemeente: "Picherande",
    afstand: "6.5 km",
    duur: "2u30",
    hoogteverschil: "215 m",
    moeilijkheid: "gemiddeld",
    beschrijving: "Dit parcours rond Picherande is tegelijk wandeling en observatiespel waarbij al uw zintuigen worden geprikkeld. Ontdek het Occitaanse patois en het leven in dit ruige bergdorp op 1130 m, omringd door meren, watervallen en veengebieden.",
    startPunt: [45.4670, 2.7760],
    hoogtepunten: ["Occitaans patois", "Bergdorp (1130 m)", "Meren en watervallen", "Observatiespel"],
    gpx: "gpx/route-19-picherande.gpx",
    url: "https://www.sancy.com/circuits/sancy-tour-parcours-decouverte-sancy/sancy-tour-n19-picherande-metait-contee/"
  },
  {
    id: 20,
    name: "Sentier du bourg et fontaine salée",
    gemeente: "Chastreix",
    afstand: "5.2 km",
    duur: "1u30",
    hoogteverschil: "131 m",
    moeilijkheid: "gemiddeld",
    beschrijving: "Kristell en Remi onthullen het verhaal van de Vallei van de Fontaine Salee in het Nationaal Natuurreservaat Chastreix-Sancy. Een van de mooiste wandelingen met grandioze vergezichten op de zuidkant van de Puy de Sancy. Let op: honden verboden!",
    startPunt: [45.5160, 2.7310],
    hoogtepunten: ["Natuurreservaat Chastreix-Sancy", "Fontaine Salee", "Panorama Puy de Sancy", "Glaciaal keteldal"],
    gpx: "gpx/route-20-chastreix.gpx",
    url: "https://www.sancy.com/circuits/sancy-tour-parcours-decouverte-sancy/sancy-tour-n-20-cirque-de-fontaine-salee-chastreix/"
  }
];

const TOWNS = [
  { name: "Le Mont-Dore", coords: [45.5736, 2.8081], voorzieningen: ["thermes", "camping", "gite", "piscine", "tennis"] },
  { name: "La Bourboule", coords: [45.5878, 2.7381], voorzieningen: ["thermes", "camping", "piscine", "tennis", "escalade"] },
  { name: "Murat-le-Quaire", coords: [45.5970, 2.7530], voorzieningen: ["gite", "camping"] },
  { name: "Chambon-sur-Lac", coords: [45.5690, 2.8700], voorzieningen: ["camping", "piscine", "equitation"] },
  { name: "Murol", coords: [45.5720, 2.9450], voorzieningen: ["camping", "gite", "piscine", "equitation"] },
  { name: "Saint-Nectaire", coords: [45.5870, 2.9930], voorzieningen: ["thermes", "camping", "gite"] },
  { name: "Super-Besse", coords: [45.5070, 2.8510], voorzieningen: ["camping", "piscine", "escalade"] },
  { name: "Besse-et-Saint-Anastaise", coords: [45.5120, 2.9370], voorzieningen: ["camping", "gite", "piscine"] },
  { name: "Saint-Victor-la-Rivière", coords: [45.5350, 2.9550], voorzieningen: ["gite"] },
  { name: "Chastreix", coords: [45.5160, 2.7310], voorzieningen: ["gite", "camping"] },
  { name: "Picherande", coords: [45.4670, 2.7760], voorzieningen: ["gite", "camping"] },
  { name: "Saint-Pierre-Colamine", coords: [45.5450, 2.9830], voorzieningen: ["gite"] },
  { name: "Le Vernet-Sainte-Marguerite", coords: [45.6050, 2.9200], voorzieningen: [] },
  { name: "Egliseneuve-d'Entraigues", coords: [45.4080, 2.8261], voorzieningen: ["camping", "gite"] },
  { name: "Compains", coords: [45.4300, 2.9600], voorzieningen: ["gite"] },
  { name: "La Godivelle", coords: [45.3890, 2.8860], voorzieningen: [] },
  { name: "Espinchal", coords: [45.4150, 2.9350], voorzieningen: [] },
  { name: "Saint-Genès-Champespe", coords: [45.4450, 2.7650], voorzieningen: ["gite"] },
  { name: "Valbeleix", coords: [45.4540, 2.9750], voorzieningen: [] },
  { name: "Saint-Diéry", coords: [45.5610, 2.9750], voorzieningen: [] },
  { name: "Montgreleix", coords: [45.4290, 2.8100], voorzieningen: [] }
];

const POINTS_OF_INTEREST = [
  { name: "Puy de Sancy", type: "sommet", coords: [45.5293, 2.8142], hoogte: "1886 m", beschrijving: "Hoogste punt van het Centraal Massief" },
  { name: "Lac Pavin", type: "meer", coords: [45.4960, 2.8890], hoogte: "1197 m", beschrijving: "Mysterieus kratermeer van vulkanische oorsprong" },
  { name: "Lac Chambon", type: "meer", coords: [45.5730, 2.8650], hoogte: "877 m", beschrijving: "Groot meer aan de voet van het Château de Murol" },
  { name: "Cascades d'Entraigues", type: "waterval", coords: [45.4170, 2.9050], hoogte: null, beschrijving: "Schilderachtige watervallen bij Entraigues" },
  { name: "Cascade du Bois de Chaux", type: "waterval", coords: [45.4190, 2.9100], hoogte: null, beschrijving: "Waterval in het Bois de Chaux" },
  { name: "Grande Cascade du Mont-Dore", type: "waterval", coords: [45.5600, 2.8000], hoogte: null, beschrijving: "Hoogste waterval van de Auvergne (30m)" },
  { name: "Vallée de Chaudefour", type: "natuurreservaat", coords: [45.5420, 2.8450], hoogte: null, beschrijving: "Nationaal natuurreservaat met unieke fauna en flora" },
  { name: "Grottes Jonas", type: "bezienswaardigheid", coords: [45.5430, 2.9810], hoogte: null, beschrijving: "Middeleeuwse grotwoningen uitgehakt in de rots" },
  { name: "Château de Murol", type: "bezienswaardigheid", coords: [45.5735, 2.9430], hoogte: "1050 m", beschrijving: "Imposant middeleeuws kasteel uit de 12e eeuw" },
  { name: "Lac d'en Haut (La Godivelle)", type: "meer", coords: [45.3920, 2.8830], hoogte: "1239 m", beschrijving: "Beschermd kratermeer, een van de mooiste van de Auvergne" },
  { name: "Station de Chastreix-Sancy", type: "skistation", coords: [45.5100, 2.7450], hoogte: "1350 m", beschrijving: "Klein skistation aan de zuidzijde van de Sancy" },
  { name: "Station du Mont-Dore", type: "skistation", coords: [45.5500, 2.8050], hoogte: "1350 m", beschrijving: "Skistation van Le Mont-Dore" }
];

// Voorzieningen iconen mapping
const VOORZIENINGEN_ICONS = {
  thermes: { label: "Thermen", icon: "\u{1F3DB}\uFE0F" },
  camping: { label: "Camping", icon: "\u26FA" },
  gite: { label: "G\u00EEte d'\u00E9tape", icon: "\u{1F3E0}" },
  piscine: { label: "Zwembad", icon: "\u{1F3CA}" },
  equitation: { label: "Paardrijden", icon: "\u{1F434}" },
  escalade: { label: "Klimmen", icon: "\u{1F9D7}" },
  tennis: { label: "Tennis", icon: "\u{1F3BE}" },
  accrobranche: { label: "Klimbos", icon: "\u{1F333}" }
};
